name: Build and Package EXE Installer

on:
  push:
    branches:
      - main

jobs:
  jpackage-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' 

      - name: Run jpackage command to create the EXE
        run: |
          # PowerShell line continuation uses backtick `
          jpackage `
            --type exe `
            --name barcode-pdf-generator `
            --input target `
            --main-jar barcode-pdf-generator-0.0.1-SNAPSHOT.jar `
            --main-class com.ricoom.barcode.BarcodePdfGridGenerator `
            --runtime-image runtime `
            --dest dist `
            --icon app-icon.ico `
            --win-menu `
            --win-shortcut `
            --vendor "Eric Mwaniki Munene" `
            --description "BarcodePdfGridGenerator Application." `
            --app-version "1.0.0" `
            --copyright "Â© 2025 Eric Mwaniki Munene" `
            --license-file license.txt

      - name: Upload the resulting EXE installer as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: BarcodePDFGenerator-Installer
          path: dist/barcode-pdf-generator-1.0.0.exe
          retention-days: 7 

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2 
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/barcode-pdf-generator-1.0.0.exe
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
